//! Write `/dev/disk/by-id/` facts as a Nix-importable file for disko.
//!
//! Replaces the hand-rolled shell placeholder in pleme-io/nix's
//! `modules/pleme/nixos/disk-facts.nix` (the module that named `disco` as its
//! destination tool — seibi is that home). Enumerates the stable by-id
//! symlinks for nvme/ata/scsi/wwn whole disks, resolves each to its kernel
//! device name, and emits:
//!
//! ```nix
//! { byId = { "nvme-Samsung_..." = "nvme0n1"; ... };
//!   nvmes = [ "nvme0n1" "nvme1n1" ]; }
//! ```
//!
//! Designed for a `Type=oneshot` systemd service triggered at boot + on any
//! block-device udev change, so disko can `import` stable identifiers without
//! the operator hand-pasting them.
//!
//! Nix is emitted through a typed `Display` impl (TYPED EMISSION — no
//! `format!()` of Nix syntax; the impl block is the render surface).

use anyhow::{Context, Result};
use clap::Args as ClapArgs;
use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::process::ExitCode;
use tracing::info;

#[derive(ClapArgs)]
pub struct Args {
    /// Where the facts file is written.
    #[arg(long, default_value = "/var/lib/pleme/disk-facts.nix")]
    out: PathBuf,

    /// Record full by-id paths (which contain serial numbers). Pass to omit
    /// them on secrecy-sensitive deployments (the byId map is then empty; the
    /// nvmes list is still emitted).
    #[arg(long)]
    no_serials: bool,

    /// Directory of by-id symlinks (override for tests).
    #[arg(long, default_value = "/dev/disk/by-id", hide = true)]
    by_id_dir: PathBuf,

    /// Directory of block devices, for the nvmes list (override for tests).
    #[arg(long, default_value = "/dev", hide = true)]
    dev_dir: PathBuf,
}

/// The whole-disk by-id prefixes we record (partitions are filtered out).
const BY_ID_PREFIXES: &[&str] = &["nvme-", "ata-", "scsi-", "wwn-"];

/// Typed facts value — the Nix render surface lives in its `Display` impl.
struct DiskFacts {
    /// by-id symlink name -> kernel device name (whole disks only).
    by_id: BTreeMap<String, String>,
    /// whole nvme namespace-1 devices (e.g. `nvme0n1`), sorted.
    nvmes: Vec<String>,
}

impl fmt::Display for DiskFacts {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "# AUTO-GENERATED by `seibi disk-facts` — do not edit.")?;
        writeln!(f, "# Consumed by disko.nix via lib/disk-facts.nix helper.")?;
        writeln!(f, "{{")?;
        writeln!(f, "  byId = {{")?;
        for (link, dev) in &self.by_id {
            writeln!(f, "    {:?} = {:?};", link, dev)?;
        }
        writeln!(f, "  }};")?;
        writeln!(f, "  nvmes = [")?;
        for dev in &self.nvmes {
            writeln!(f, "    {:?}", dev)?;
        }
        writeln!(f, "  ];")?;
        write!(f, "}}")
    }
}

/// A kernel device name is a PARTITION (not a whole disk) when:
///   - nvme: `nvmeXnYpZ` (a `p` after the namespace) — whole disk is `nvmeXnY`;
///   - sd/vd: the name ends in a digit (`sda1`) — whole disk is `sda`.
fn is_partition(dev: &str) -> bool {
    if let Some(rest) = dev.strip_prefix("nvme") {
        return rest.contains('p');
    }
    if dev.starts_with("sd") || dev.starts_with("vd") {
        return dev.chars().last().is_some_and(|c| c.is_ascii_digit());
    }
    false
}

fn has_recorded_prefix(name: &str) -> bool {
    BY_ID_PREFIXES.iter().any(|p| name.starts_with(p))
}

/// Gather the by-id -> whole-disk map by resolving each recorded symlink.
fn gather_by_id(by_id_dir: &PathBuf) -> Result<BTreeMap<String, String>> {
    let mut map = BTreeMap::new();
    let entries = match fs::read_dir(by_id_dir) {
        Ok(e) => e,
        // No by-id dir (e.g. a VM with no stable links) is not an error — the
        // facts file is just empty; disko falls back to by-index paths.
        Err(_) => return Ok(map),
    };
    for entry in entries {
        let entry = entry.context("reading a by-id entry")?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if !has_recorded_prefix(&name) {
            continue;
        }
        let target = fs::canonicalize(entry.path())
            .with_context(|| format!("resolving symlink {name}"))?;
        let dev = match target.file_name() {
            Some(d) => d.to_string_lossy().into_owned(),
            None => continue,
        };
        if is_partition(&dev) {
            continue;
        }
        map.insert(name, dev);
    }
    Ok(map)
}

/// Gather the nvme namespace-1 whole-disk list (`/dev/nvme*n1`).
fn gather_nvmes(dev_dir: &PathBuf) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let entries = match fs::read_dir(dev_dir) {
        Ok(e) => e,
        Err(_) => return Ok(out),
    };
    for entry in entries {
        let entry = entry.context("reading a /dev entry")?;
        let name = entry.file_name().to_string_lossy().into_owned();
        // nvmeXn1 whole namespace-1 disks only (no partition `p`, ends `n1`).
        if name.starts_with("nvme") && name.ends_with("n1") && !name.contains('p') {
            out.push(name);
        }
    }
    out.sort();
    Ok(out)
}

pub fn run(args: &Args) -> Result<ExitCode> {
    let by_id = if args.no_serials {
        BTreeMap::new()
    } else {
        gather_by_id(&args.by_id_dir)?
    };
    let nvmes = gather_nvmes(&args.dev_dir)?;

    let facts = DiskFacts { by_id, nvmes };
    let rendered = format!("{facts}\n");

    if let Some(parent) = args.out.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&args.out, &rendered)
        .with_context(|| format!("writing {}", args.out.display()))?;
    // Read-only — disko only ever imports it.
    let mut perms = fs::metadata(&args.out)?.permissions();
    perms.set_mode(0o444);
    fs::set_permissions(&args.out, perms)?;

    info!(
        out = %args.out.display(),
        by_id = facts.by_id.len(),
        nvmes = facts.nvmes.len(),
        "disk facts written"
    );
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn partition_detection() {
        assert!(!is_partition("nvme0n1"));
        assert!(is_partition("nvme0n1p1"));
        assert!(is_partition("nvme1n1p2"));
        assert!(!is_partition("sda"));
        assert!(is_partition("sda1"));
        assert!(!is_partition("vdb"));
        assert!(is_partition("vdb2"));
    }

    #[test]
    fn recorded_prefixes() {
        assert!(has_recorded_prefix("nvme-Samsung_SSD_990"));
        assert!(has_recorded_prefix("ata-CT500"));
        assert!(has_recorded_prefix("wwn-0x5001"));
        assert!(!has_recorded_prefix("usb-Generic"));
        assert!(!has_recorded_prefix("dm-name-foo"));
    }

    #[test]
    fn renders_stable_nix() {
        let mut by_id = BTreeMap::new();
        by_id.insert("nvme-Samsung_990-1".to_string(), "nvme0n1".to_string());
        by_id.insert("ata-CT500-1".to_string(), "sda".to_string());
        let facts = DiskFacts {
            by_id,
            nvmes: vec!["nvme0n1".to_string(), "nvme1n1".to_string()],
        };
        let s = facts.to_string();
        // Deterministic (BTreeMap sorts), quoted, importable.
        assert!(s.contains(r#"    "ata-CT500-1" = "sda";"#));
        assert!(s.contains(r#"    "nvme-Samsung_990-1" = "nvme0n1";"#));
        assert!(s.contains(r#"    "nvme0n1""#));
        assert!(s.contains("byId = {"));
        assert!(s.contains("nvmes = ["));
        // ata sorts before nvme (the map is ordered).
        let ata = s.find("ata-CT500").unwrap();
        let nvme = s.find("nvme-Samsung").unwrap();
        assert!(ata < nvme);
    }

    #[test]
    fn empty_facts_render() {
        let facts = DiskFacts {
            by_id: BTreeMap::new(),
            nvmes: vec![],
        };
        let s = facts.to_string();
        assert!(s.contains("byId = {"));
        assert!(s.contains("nvmes = ["));
        assert!(s.trim_end().ends_with('}'));
    }
}
